// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnkskltswbuupxgdcyuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNua3NrbHRzd2J1dXB4Z2RjeXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MDM4MzEsImV4cCI6MjA5MDQ3OTgzMX0.nIaSPNFEq9T7qwMXfyX23AQWV8_fWjcfJieRJFvr4-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});